hivemq/hivemq-mqtt-client-dotnet

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/IHiveMQClient.cs
Source/HiveMQtt/Client/Options/HiveMQClientOptions.cs
Source/HiveMQtt/MQTT5/Packets/ConnectPacket.cs
Source/HiveMQtt/MQTT5/ReasonCodes/AuthReasonCode.cs

Initial TLS and basic auth support

---

Source/HiveMQtt/MQTT5/ControlPacket.cs
Source/HiveMQtt/MQTT5/Packets/ConnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/DisconnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/PingReqPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubCompPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubRecPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubRelPacket.cs
Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs
Source/HiveMQtt/MQTT5/Packets/SubscribePacket.cs
Source/HiveMQtt/MQTT5/Packets/UnsubscribePacket.cs

Update MemoryStream use pattern

---

.github/workflows/build.yml
.gitignore
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/HiveMQtt.csproj
Tests/HiveMQtt.Test/HiveMQClient/HiveMQClientConnectTest.cs
Tests/HiveMQtt.Test/HiveMQClient/HiveMQClientPubSubTest.cs
Tests/HiveMQtt.Test/HiveMQtt.Test.csproj
build.cake
dotnet-tools.json

Test Suite Improvements

---

Images/csharp-logo.png
Images/hivemq-mqtt-client.png
README.md

NuGet.org: Update README to be compatible

---

Documentation/Events.md
Documentation/Examples.md
README.md

Documentation Updates

---

Documentation/Events.md
Documentation/Examples.md
README.md

- Use fully qualified links for NuGet
- More examples

More Examples & Use Fully Qualified Links

---

Examples/HiveMQtt-CLI/HiveMQtt-CLI.sln
Examples/HiveMQtt-CLI/HiveMQtt-CLI/HiveMQtt-CLI.csproj
Examples/HiveMQtt-CLI/HiveMQtt-CLI/Program.cs
Examples/HiveMQtt-CLI/README.md
Source/HiveMQtt/Client/Results/ConnectResult.cs

Examples: Add console application that uses the HiveMQtt NuGet package

---

.github/workflows/build.yml

Github Action: enable cake pack

---

.github/workflows/build.yml

Github Actions: Fix Nuget Push

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Source/HiveMQtt/Client/Options/SubscribeOptions.cs
Source/HiveMQtt/Client/Options/UnsubscribeOptions.cs
Source/HiveMQtt/Client/Results/SubscribeResult.cs
Source/HiveMQtt/MQTT5/ControlPacket.cs
Source/HiveMQtt/MQTT5/PacketDecoder.cs
Source/HiveMQtt/MQTT5/Packets/ConnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/DisconnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubCompPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubRecPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubRelPacket.cs
Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs
Source/HiveMQtt/MQTT5/Packets/SubAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/SubscribePacket.cs
Source/HiveMQtt/MQTT5/Packets/UnsubAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/UnsubscribePacket.cs

Refactoring, Cleanup & More Code Documentation

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Source/HiveMQtt/Client/Options/SubscribeOptions.cs
Source/HiveMQtt/Client/Options/UnsubscribeOptions.cs
Source/HiveMQtt/Client/Results/SubscribeResult.cs
Source/HiveMQtt/MQTT5/ControlPacket.cs
Source/HiveMQtt/MQTT5/PacketDecoder.cs
Source/HiveMQtt/MQTT5/Packets/ConnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/DisconnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubCompPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubRecPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubRelPacket.cs
Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs
Source/HiveMQtt/MQTT5/Packets/SubAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/SubscribePacket.cs
Source/HiveMQtt/MQTT5/Packets/UnsubAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/UnsubscribePacket.cs
StyleCop.Analyzers.ruleset

This reorganises some components and cleans up a subset of the warnings.
- Centralize Packet ID decoding; Cleanup & Code Docs
- Reduce warnings

Refactoring and Cleanup

---

Directory.Build.props
README.md
Source/Directory.Build.props
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientEvents.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Source/HiveMQtt/Client/LastWillAndTestament.cs
Source/HiveMQtt/Client/Options/DisconnectOptions.cs
Source/HiveMQtt/Client/Options/HiveMQClientOptions.cs
Source/HiveMQtt/Client/Results/SubscribeResult.cs
Source/HiveMQtt/HiveMQtt.csproj
Source/HiveMQtt/MQTT5/ControlPacket.cs
Source/HiveMQtt/MQTT5/Packets/ConnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/DisconnectPacket.cs
Source/HiveMQtt/MQTT5/Types/MQTT5LastWillProperties.cs
Source/HiveMQtt/MQTT5/Types/MQTT5Properties.cs
Source/HiveMQtt/MQTT5/Types/VariableByteInteger.cs
Source/HiveMQtt/Properties/AssemblyInfo.cs
StyleCop.Analyzers.ruleset
Tests/HiveMQtt.Test/HiveMQClient/HiveMQClientConnectOptionsTest.cs
Tests/HiveMQtt.Test/HiveMQClient/HiveMQClientConnectTest.cs
Tests/HiveMQtt.Test/HiveMQClient/HiveMQClientLWTTest.cs
Tests/HiveMQtt.Test/HiveMQClient/HiveMQClientOptionsTest.cs
Tests/HiveMQtt.Test/HiveMQClient/HiveMQClientPubSubTest.cs
Tests/HiveMQtt.Test/Packets/ControlPacketTest.cs
stylecop.json

This PR adds Last Will and Testament support to the client and also fixes a couple bugs.

Add Last Will and Testament Support

---

Examples/Reconnect/Program.cs
Examples/Reconnect/Reconnect.csproj
Source/HiveMQtt/Client/HiveMQClientSocket.cs

Fix Cancellation Token Reset

---

Source/HiveMQtt/Client/Events/OnPublishQoS2CompleteEventArgs.cs
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/MQTT5/PacketDecoder.cs
Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs

Fixes #98
This PR improves the entire traffic processing pipeline.
- Better Pipeline behaviour
- Rebuilt core incoming traffic processor

Improved (and faster) Traffic Processing

---

Examples/ConnectReceiveAndPublish/.vscode/launch.json
Examples/ConnectReceiveAndPublish/.vscode/tasks.json
Examples/ConnectReceiveAndPublish/ConnectReceiveAndPublish.csproj
Examples/ConnectReceiveAndPublish/Program.cs
Examples/ConnectReceiveAndPublish/README.md
Examples/Reconnect/README.md
Examples/SendMessageOnLoop/.vscode/launch.json
Examples/SendMessageOnLoop/.vscode/tasks.json
Examples/SendMessageOnLoop/Program.cs
Examples/SendMessageOnLoop/README.md
Examples/SendMessageOnLoop/SendMessageOnLoop.csproj

- Add new SendMessageOnLoop example
- The whole bloody affair

New & Updated Example Applications, Tools and Utilities

---

Directory.Build.props

Update the NuGet page with the new documentation URL.

Update NuGet Package Details

---

Tests/HiveMQtt.Test/HiveMQClient/LWTTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LastWillAndTestamentBuilderTest.cs

Increase timeout for Github hosted broker

---

Source/HiveMQtt/HiveMQtt.csproj

NuGet: Updated Metadata

---

Source/HiveMQtt/Client/HiveMQClientEvents.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Tests/HiveMQtt.Test/HiveMQClient/SubscribeBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/UtilTest.cs

This adds the regular expression matching for MQTT topic wildcards.
- Wildcard fixes and moar tests
- Topic Matching
Fixed #126

Better Topic Matching

---

.editorconfig
.vscode/launch.json
.vscode/tasks.json
Benchmarks/ClientBenchmarkApp/ClientBenchmark.cs
Benchmarks/ClientBenchmarkApp/ClientBenchmarkApp.csproj
Benchmarks/ClientBenchmarkApp/Program.cs
Benchmarks/ClientBenchmarkApp/README.md
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Source/HiveMQtt/Client/PublishMessageBuilder.cs
Source/HiveMQtt/Client/Results/UnsubscribeResult.cs
Source/HiveMQtt/Client/SubscribeOptionsBuilder.cs
Source/HiveMQtt/Client/UnsubscribeOptionsBuilder.cs

Performance Benchmarks

---

Benchmarks/ClientBenchmarkApp/ClientBenchmark.cs
Documentation/docs/how-to/configure-logging.md
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientOptionsBuilder.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Source/HiveMQtt/MQTT5/PacketDecoder.cs
Tests/HiveMQtt.Test/HiveMQClient/OptionsTest.cs

This PR improves the performance of the client.
Results as of now are as follows:

Performance Improvements

---

.github/workflows/build.yml
Benchmarks/ClientBenchmarkApp/README.md
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Source/HiveMQtt/Client/Options/HiveMQClientOptions.cs
Source/HiveMQtt/HiveMQtt.csproj
Source/HiveMQtt/MQTT5/Packets/ConnectPacket.cs
Tests/HiveMQtt.Test/HiveMQClient/ClientTest.cs
Tests/HiveMQtt.Test/HiveMQClient/ConnectOptions.cs
Tests/HiveMQtt.Test/HiveMQClient/OptionsTest.cs
Tests/HiveMQtt.Test/HiveMQtt.Test.csproj
Tests/HiveMQtt.Test/xunit.runner.json

Client Stability & Test Suite Improvements

---

README.md

Fix example of README

---

Benchmarks/ClientBenchmarkApp/ClientBenchmark.cs

Benchmarks: Add Variable Payload Size Benchmarks

---

Tests/HiveMQtt.Test/HiveMQClient/ConnectTest.cs

More Test & Client Validations

---

Documentation/docs/benchmarks.md
Documentation/docs/intro.md
Documentation/docs/quickstart.md
Documentation/src/components/HomepageIntro/index.js
README.md

- **Better BETA message**
- **Fix intro and copyright**
- **Add Benchmark documentation**

March Documentation Updates

---

Benchmarks/ClientBenchmarkApp/ClientBenchmark.cs
Examples/ConnectReceiveAndPublish/ConnectReceiveAndPublish.csproj
Examples/Reconnect/Program.cs
Examples/Reconnect/Reconnect.csproj
Examples/SendMessageOnLoop/SendMessageOnLoop.csproj

Examples: Update dependencies & fix warnings

---

.github/workflows/build.yml

Tests: Expand Test Matrix with .NET 6, 7 & 8

---

.editorconfig
Benchmarks/ClientBenchmarkApp/ClientBenchmark.cs

.NET 8: Fix Warnings

---

Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs

Event: Fix missing OnPublishReceivedEvent

---

.vscode/tasks.json
Examples/SubscriberWithEvents/Program.cs
Examples/SubscriberWithEvents/README.md
Examples/SubscriberWithEvents/SubscriberWithEvents.csproj

Example: SubscriberWithEvents

---

.vscode/launch.json
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/HiveMQtt.csproj
Source/HiveMQtt/MQTT5/ControlPacket.cs
Source/HiveMQtt/MQTT5/Packets/ConnAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/DisconnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubCompPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubRecPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubRelPacket.cs
Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs
Source/HiveMQtt/MQTT5/Packets/SubAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/UnsubAckPacket.cs
Tests/HiveMQtt.Test/HiveMQClient/ClientTest.cs
Tests/HiveMQtt.Test/HiveMQtt.Test.csproj
global.json

Client Receive Maximum: Enforcement Check

---

Documentation/docs/connecting.md
Documentation/docs/events/_category_.json
Documentation/docs/how-to/_category_.json
Documentation/docs/intro.md
Documentation/docs/namespaces.md
Documentation/docs/publishing.md
Documentation/docs/quickstart.md
Documentation/docs/reference/_category_.json
Documentation/docs/reference/client_options.md
Documentation/docs/reference/client_options_builder.md
Documentation/docs/reference/disconnect_options.md
Documentation/docs/subscribing.md

New Reference Documentation

---

Benchmarks/ClientBenchmarkApp/ClientBenchmarkApp.csproj
Examples/ConnectReceiveAndPublish/ConnectReceiveAndPublish.csproj
Examples/HiveMQtt-CLI/HiveMQtt-CLI/HiveMQtt-CLI.csproj
Examples/Reconnect/Reconnect.csproj

Update Examples to .NET 8.0

---

Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/HiveMQClient/SubscribeBuilderTest.cs

And skip inconsistent tests that are failing only on Github CI.  To be fixed on next release.

Tests: Use WhenAny

---

Source/HiveMQtt/Client/HiveMQClientEvents.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Tests/.editorconfig
Tests/HiveMQtt.Test/HiveMQClient/ClientTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LWTTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LastWillAndTestamentBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/Operational/QueuedPublishesTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PubSubTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/HiveMQClient/SubscribeBuilderTest.cs

Fix Connection Check in Publish Writer Task

---

.github/workflows/build.yml
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientEvents.cs
Source/HiveMQtt/HiveMQtt.csproj

Github CI: Build and push multi-arch package

---

.github/workflows/build.yml

Fix for the new NuGet package pushing strategy.

CI: Store Artifacts across builds

---

Source/HiveMQtt/HiveMQtt.csproj
Tests/HiveMQtt.Test/HiveMQClient/Operational/QueuedPublishesTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/HiveMQtt.Test.csproj

Improved Package Spec & Reduced Warnings

---

Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs

This PR adds some health checks to internal systems and disconnects if anything is out of order.

Add Periodic Internal Health Checks

---

Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/MQTT5/Packets/SubscribePacket.cs

Improved Behaviour in Error Situations

---

Tests/HiveMQtt.Test/HiveMQClient/ClientOptionsTest.cs
Tests/HiveMQtt.Test/HiveMQClient/ConnectTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LWTTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LastWillAndTestamentBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/Operational/QueuedPublishesTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PubSubTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/HiveMQClient/SubscribeBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/SubscribeTest.cs
Tests/HiveMQtt.Test/HiveMQClient/UnsubscribeBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/UnsubscribeTest.cs

Tests: Used named clients

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Source/HiveMQtt/Client/Options/HiveMQClientOptions.cs
Source/HiveMQtt/Client/internal/BoundedDictionaryX.cs
Source/HiveMQtt/Client/internal/PacketIDManagerr.cs
Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs
Source/HiveMQtt/MQTT5/Packets/UnsubscribePacket.cs

This PR introduces improved packet ID generation and also fixes a bug where the client would occasionally generate an invalidate packet ID value.

Refactor Packet ID Generation

---

Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/internal/BoundedDictionaryX.cs

Handle Retransmitted Publishes

---

Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/Options/HiveMQClientOptions.cs

Fix: Timer reset only on egress

---

Documentation/docs/connecting.md
Documentation/yarn.lock

Documentation Updates: Bundle upgrades & WebSockets

---

Documentation/docs/reference/disconnect_options_builder.md
Documentation/docs/reference/last_will_and_testament.md
Documentation/docs/reference/last_will_and_testament_builder.md
Documentation/docs/reference/publish_message.md
Documentation/docs/reference/publish_message_builder.md
Documentation/docs/reference/subscribe_options.md
Documentation/docs/reference/subscribe_options_builder.md
Documentation/docs/reference/unsubscribe_options.md
Documentation/docs/reference/unsubscribe_options_builder.md

Documentation: Docs for all the classes & builders

---

Documentation/yarn.lock

Security & Dependency Updates

---

Documentation/package-lock.json
Documentation/yarn.lock

Dependency Updates

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs
Source/HiveMQtt/MQTT5/Packets/SubscribePacket.cs
Tests/HiveMQtt.Test/HiveMQClient/ConnectTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LWTTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LastWillAndTestamentBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/Plan/PacketRestrictionsTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PubSubTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/HiveMQClient/SubscribeBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/WebSocket/ConnectTest.cs
Tests/HiveMQtt.Test/HiveMQClient/WebSocket/PubSubTest.cs
Tests/HiveMQtt.Test/HiveMQClient/WebSocket/PublishTest.cs

Per [this documentation](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#always-create-taskcompletionsourcet-with-taskcreationoptionsruncontinuationsasynchronously).
This was a great suggestion by @JaggerJo - thanks!

TaskCompletionSource: Use TaskCreationOptions.RunContinuationsAsynchronously

---

Source/HiveMQtt/Client/IHiveMQClient.cs

Add documented events to the public interface.

IHiveMQClient: Add Public Events to Interface
