Source/HiveMQtt/Client/Options/HiveMQClientOptions.cs

Port 8883 is [registered with IANA](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=mqtt) as "secure MQTT".  When the client is configured to use this port, enable TLS by default.
If for some reason a user wants to disable this, they can use the `BeforeConnect` event handler and set `UseTLS` to false.
Fixes #54

When port 8883, default to TLS

---

Examples/Reconnect/.vscode/launch.json
Examples/Reconnect/.vscode/tasks.json
Examples/Reconnect/Program.cs
Examples/Reconnect/Reconnect.csproj
Source/HiveMQtt/Client/Events/AfterDisconnectEventArgs.cs
Source/HiveMQtt/Client/Events/BeforeDisconnectEventArgs.cs
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientEvents.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Tests/HiveMQtt.Test/HiveMQClient/HiveMQClientConnectTest.cs
Tests/HiveMQtt.Test/HiveMQClient/HiveMQClientPubSubTest.cs

Add Support for [After|Before]Disconnect Events

---

Examples/Reconnect/Program.cs
Examples/Reconnect/Reconnect.csproj
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs

- Add Trace statements
- Add delay to Example/Reconnect to assure the AfterDisconnect handler has time to run
- Set state after socket is closed
- Use cancellation token after socket is closed
- Set example package to link to 0.4.1

Extended AfterDisconnect Support

---

Source/HiveMQtt/MQTT5/Types/MQTT5PublishMessage.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs

Fix Publish PayloadFormatIndicator

---

Documentation/docs/how-to/set-lwt.md
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientOptionsBuilder.cs
Source/HiveMQtt/Client/LastWillAndTestament.cs
Source/HiveMQtt/Client/LastWillAndTestamentBuilder.cs
Source/HiveMQtt/Client/internal/Validator.cs
Tests/HiveMQtt.Test/HiveMQClient/LastWillAndTestamentBuilderTest.cs

This PR adds a new builder class for `LastWillAndTestament`:
```csharp
var lwt = new LastWillAndTestamentBuilder()
.WithTopic("last/will")
.WithPayload("last will message")
.WithQualityOfServiceLevel(QualityOfService.AtLeastOnceDelivery)
.WithContentType("application/text")
.WithResponseTopic("response/topic")
.WithCorrelationData(new byte[] { 1, 2, 3, 4, 5 })
.WithPayloadFormatIndicator(MQTT5PayloadFormatIndicator.UTF8Encoded)
.WithMessageExpiryInterval(100)
.WithUserProperty("userPropertyKey", "userPropertyValue")
.WithWillDelayInterval(1)
.Build();
// Setup & Connect the client with LWT
var options = new HiveMQClientOptions
{
LastWillAndTestament = lwt,
};
var client = new HiveMQClient(options);
connectResult = await client.ConnectAsync().ConfigureAwait(false);
```

New LastWillAndTestament Builder

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs

This PR adds more logging in the right places to illustrate connect/disconnect and TLS options.
How to enable/configure logging is a described in [this documentation](https://hivemq.github.io/hivemq-mqtt-client-dotnet/docs/how-to/configure-logging).
Info Level:
With Debug even more TLS information:
And the very verbose Trace:

Logging: Connect, Disconnect and TLS metadata

---

Tests/HiveMQtt.Test/HiveMQClient/LWTTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LastWillAndTestamentBuilderTest.cs

The Github tests occasionally flake out on the Last will and testament tests.  This PR increases the interval a bit to make sure we don't miss the LWT message.

Tests: More Reliable LWT Tests

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientOptionsBuilder.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs

Better Log Messages

---

Documentation/docs/how-to/configure-logging.md
Source/HiveMQtt/Client/Exceptions/HiveMQttClientException.cs
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientEvents.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Tests/HiveMQtt.Test/HiveMQClient/ConnectTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LWTTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LastWillAndTestamentBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/HiveMQClient/UnsubscribeBuilderTest.cs

This PR improves resilience from bad event handlers and QoS 2 chained publishes.

Event Handling & QoS 2 Improvements

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientEvents.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/MQTT5/PacketDecoder.cs
Source/HiveMQtt/NLog.config
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs

This PR also fixes an issue with `ReceiveMaximum`/the maximum number of concurrent transactions.

Events: Efficiency & Performance Improvements

---

Tests/HiveMQtt.Test/HiveMQClient/ConnectTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LWTTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LastWillAndTestamentBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/OptionsTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/HiveMQClient/UnsubscribeTest.cs
Tests/HiveMQtt.Test/HiveMQClient/UtilTest.cs

Test: Linter Cleanup & Improvements

---

Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/internal/AwaitableQueueX.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/Queues/AwaitableQueueXTest.cs

This PR implements a new `AwaitableQueueX` custom class that manages an underlying `ConcurrentQueue` with a semaphore that can be asynchronously awaited on.  This avoids any type of thread blocking or the need for custom (and inefficient) delays or sleeps.

Use a custom awaitable async queue

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs

With this PR, the package can now more easily wait for QoS > 1 publish packet transactions to complete:
```csharp
// QoS 1 returns the PUBACK packet
var pubAckPacket = await publishPacket.OnPublishQoS1CompleteTCS.Task.WaitAsync(...)
// QoS 2 returns all packets in transaction
List<ControlPacket> packetList;
packetList = await publishPacket.OnPublishQoS2CompleteTCS.Task.WaitAsync(...)
```
Much of the leg work of the `TaskCompletionSource` has been pushed down to the `PublishPacket` class.

Improved Wait Strategy for Individual Packets

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/Options/HiveMQClientOptions.cs
Source/HiveMQtt/MQTT5/Packets/ConnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubAckPacket.cs
Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs
Tests/HiveMQtt.Test/HiveMQClient/OptionsTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs

This PR adds the first iteration of backpressure support to limit incoming and outgoing publishes based on ReceiveMaximum.
- **Add ResponseTimeoutInMs ClientOption**
- **Lint**
- **Better OnMessageReceived launching**
- **Add Backpressure support**

Add Backpressure Support

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/internal/BoundedDictionaryX.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/Queues/BoundedDictionaryXTest.cs

New BoundedDictionary

---

Source/HiveMQtt/Client/Options/HiveMQClientOptions.cs
Source/HiveMQtt/MQTT5/Packets/SubscribePacket.cs

This PR make `SubscribePacket` awaitable for the returned SubAck.  It also ensures that we have only one subscribe in flight at any given time.

Subscribe: Better transaction management

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientSocket.cs
Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Source/HiveMQtt/Client/IHiveMQClient.cs
Source/HiveMQtt/Client/internal/BoundedDictionaryX.cs

With this PR, `PublishAsync` now blocks until the publish is executed.  This means that if we get disconnected during a publish, it will continue to block until reconnected or the task is cancelled with the new `CancellationToken` parameter.

Improved Disconnect Error Handling

---

Source/HiveMQtt/Client/HiveMQClientSocket.cs

Fix IP Address Support

---

Documentation/docs/benchmarks.md
Documentation/docs/connecting.md

Updated documentation with the results of a new benchmark run.

Documentation Updates

---

.github/workflows/release-drafter.yml
Source/HiveMQtt/Client/DisconnectOptionsBuilder.cs
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientOptionsBuilder.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Source/HiveMQtt/Client/Options/DisconnectOptions.cs
Source/HiveMQtt/Client/Options/HiveMQClientOptions.cs
Source/HiveMQtt/Client/PublishMessageBuilder.cs
Source/HiveMQtt/Client/Transport/WebSocketTransport.cs
Source/HiveMQtt/MQTT5/ControlPacket.cs
Source/HiveMQtt/MQTT5/Packets/ConnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/DisconnectPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubCompPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubRecPacket.cs
Source/HiveMQtt/MQTT5/Packets/PubRelPacket.cs
Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs
Tests/HiveMQtt.Test/HiveMQClient/Plan/Utf8LimitTest.cs
Tests/HiveMQtt.Test/HiveMQtt.Test.csproj

In the ramp up to v1, we are putting in thorough E2E tests to cover all parts of the protocol and client.
Besides extended tests, this PR includes the following fixes:
1. Fix `DecodeUTF8String` to properly handle response strings up to 65535 in length
2. Add `DisconnectOptionsBuilder` and support all options for MQTT v5 `Disconnect`
3. More limits checking on things such as Client ID length and other passed in options.

E2E Test Coverage Part 1

---

.github/workflows/build.yml
README.md
Source/HiveMQtt/Client/Connection/ConnectionManager.cs
Source/HiveMQtt/Client/Connection/ConnectionManagerTasks.cs
Source/HiveMQtt/Client/Exceptions/HiveMQttClientException.cs
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Source/HiveMQtt/Client/Transport/WebSocketTransport.cs
Source/HiveMQtt/Client/internal/Validator.cs
Source/HiveMQtt/HiveMQtt.csproj
Source/HiveMQtt/HiveMQtt.sln
Source/HiveMQtt/MQTT5/Types/TopicFilter.cs
Tests/HiveMQtt.Test/HiveMQClient/LWTTest.cs
Tests/HiveMQtt.Test/HiveMQClient/LastWillAndTestamentBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/Operational/QueuedPublishesTest.cs
Tests/HiveMQtt.Test/HiveMQClient/Plan/KeepAliveTest.cs
Tests/HiveMQtt.Test/HiveMQClient/Plan/Utf8LimitTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishBuilderTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/HiveMQClient/TLSTest.cs
Tests/HiveMQtt.Test/HiveMQClient/WebSocket/PublishTest.cs
Tests/HiveMQtt.Test/HiveMQtt.Test.csproj
Tests/HiveMQtt.Test/Queues/BoundedDictionaryXTest.cs
build.cake
dotnet-tools.json
global.json

In the ramp up to v1, we are putting in thorough E2E tests to cover all parts of the protocol and client.
Besides extended tests, this PR includes the following fixes:
1. Updated build system
2. Add support for .NET 9.0
.NET 6.0 has hit end of life on November 12, 2024 &&
.NET 7.0 has hit end of support on May 14, 2024
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

E2E Test Coverage Part 2 & Add .NET 9.0 Support

---

Source/HiveMQtt/Client/Transport/TCPTransport.cs

see issue https://github.com/hivemq/hivemq-mqtt-client-dotnet/issues/220
In short: Skip the DNS lookup if an IP was provided as Host. 
https://github.com/hivemq/hivemq-mqtt-client-dotnet/issues/220
https://github.com/hivemq/hivemq-mqtt-client-dotnet/issues/216

Avoid DNS lookup if provided an IPv4 or IPv6

---

Source/HiveMQtt/Client/HiveMQClient.cs

Check Packet Identifier when waiting for Subscription Ack/Unsubscribe Ack Package. The current implementation just takes the next one and assumes this is the matching package.
https://github.com/hivemq/hivemq-mqtt-client-dotnet/issues/222

Improved SubAck Handling:  Match packet IDs before completing event.

---

Documentation/docs/reference/connect_options.md
Documentation/docs/reference/connect_options_builder.md
Source/HiveMQtt/Client/ConnectOptionsbuilder.cs
Source/HiveMQtt/Client/Connection/ConnectionManagerHandlers.cs
Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/IHiveMQClient.cs
Source/HiveMQtt/Client/Options/ConnectOptions.cs
Source/HiveMQtt/Client/Transport/WebSocketTransport.cs
Source/HiveMQtt/Client/internal/BoundedDictionaryX.cs
Source/HiveMQtt/Client/internal/Validator.cs
Source/HiveMQtt/MQTT5/Types/MQTT5PublishMessage.cs
Tests/HiveMQtt.Test/HiveMQClient/ConnectTest.cs
Tests/HiveMQtt.Test/HiveMQClient/Plan/PacketRestrictionsTest.cs
Tests/HiveMQtt.Test/HiveMQClient/Plan/SessionExpiryTest.cs
Tests/HiveMQtt.Test/HiveMQClient/PublishTest.cs
Tests/HiveMQtt.Test/HiveMQClient/TLSTest.cs
Tests/HiveMQtt.Test/HiveMQClient/WebSocket/ConnectTest.cs

* New optional `ConnectOptions` class and related builder (and documentation)
* Reset in-flight/mid-transaction messages on connect when session present == false
* Lower QoS if outgoing publishes if it exceeds broker communicated max QoS
* Set default QoS if not specified in PublishAsync
* Other general improvements & tests in preparation for v1.0.

ConnectOptions & v1.0 Test Plan Updates

---

Source/HiveMQtt/Client/HiveMQClient.cs
Source/HiveMQtt/Client/HiveMQClientEvents.cs
Source/HiveMQtt/Client/HiveMQClientUtil.cs
Tests/HiveMQtt.Test/HiveMQClient/ThreadSafeSubscribeUnsubscribeTest.cs

Every access of the Subscriptions property is now locked with a semaphore. User of the client should not access the Subscriptions, also this property is public, because they can not lock the access. Later the Subscriptions should not be public and be perhaps of type ConcurrentBag.
https://github.com/hivemq/hivemq-mqtt-client-dotnet/issues/225

fix: lock subscriptions
